# Generated by Django 5.0.3 on 2024-03-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the branch name', max_length=100, verbose_name='Branch Name')),
                ('address', models.TextField(help_text='Enter the branch address', verbose_name='Branch Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter your customer name', max_length=100, verbose_name='Name')),
                ('email', models.EmailField(help_text='Enter your valid email address', max_length=254, unique=True, verbose_name='Email address')),
                ('address', models.TextField(help_text='Enter your address', verbose_name='Address')),
                ('phone', models.CharField(help_text='Enter your phone number', max_length=10, verbose_name='Phone Number')),
                ('password', models.CharField(help_text='Enter your password', max_length=100, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter your employee name', max_length=100, verbose_name='Name')),
                ('email', models.EmailField(help_text='Enter your valid email address', max_length=254, unique=True, verbose_name='Email address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the task title', max_length=100, verbose_name='Task Title')),
                ('description', models.TextField(help_text='Enter the task description', verbose_name='Task Description')),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Branch Manager', 'Branch Manager'), ('Customer', 'Customer')], max_length=50, verbose_name='Role')),
                ('url', models.CharField(help_text='Enter the task URL', max_length=100, verbose_name='Task URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter your employee name', max_length=100, verbose_name='Name')),
                ('email', models.EmailField(help_text='Enter your valid email address', max_length=254, unique=True, verbose_name='Email address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.branch')),
            ],
            options={
                'verbose_name': 'Branch Manager',
                'verbose_name_plural': 'Branch Managers',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(help_text='Enter the driver license number', max_length=100, unique=True, verbose_name='License Number')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.branch')),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
                'ordering': ['license_number'],
            },
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField(help_text='Enter the consignment weight', verbose_name='Consignment Weight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_branch', to='transport.branch')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_branch', to='transport.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.customer')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.truck')),
            ],
            options={
                'verbose_name': 'Consignment',
                'verbose_name_plural': 'Consignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
