# Generated by Django 5.0.3 on 2024-03-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Truck Assigned', 'Truck Assigned'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=50, verbose_name='Consignment Status'),
        ),
    ]
