# Generated by Django 5.0.3 on 2024-03-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_consignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='request_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='Request Method'),
        ),
    ]
