# Generated by Django 5.0.3 on 2024-04-03 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_tasks_request_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='truck',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='transport.truck'),
        ),
        migrations.CreateModel(
            name='WaitingTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('waiting_time', models.FloatField(help_text='Enter the waiting time in hours', verbose_name='Waiting Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.consignment')),
            ],
            options={
                'verbose_name': 'Waiting Time',
                'verbose_name_plural': 'Waiting Times',
                'ordering': ['-created_at'],
            },
        ),
    ]
