# Generated by Django 5.0.3 on 2024-04-03 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_consignment_truck_waitingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingtime',
            name='consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.consignment', unique=True),
        ),
    ]
